// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKwymEyUaZH3NB7uZTPwgfle9FPk9KfRY',
    appId: '1:548212632447:web:aedad807d3cf29026c084a',
    messagingSenderId: '548212632447',
    projectId: 'sportify-38715',
    authDomain: 'sportify-38715.firebaseapp.com',
    storageBucket: 'sportify-38715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqGYbAlYB69P7kqzgALpnAsNwyTdtA4FQ',
    appId: '1:548212632447:android:8b1e4fbd3a5c61916c084a',
    messagingSenderId: '548212632447',
    projectId: 'sportify-38715',
    storageBucket: 'sportify-38715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLR1CZsqCWOzuxprcFl8oC0XXosTH6rDQ',
    appId: '1:548212632447:ios:8182c1d68be97a5c6c084a',
    messagingSenderId: '548212632447',
    projectId: 'sportify-38715',
    storageBucket: 'sportify-38715.appspot.com',
    iosBundleId: 'com.example.toi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLR1CZsqCWOzuxprcFl8oC0XXosTH6rDQ',
    appId: '1:548212632447:ios:8182c1d68be97a5c6c084a',
    messagingSenderId: '548212632447',
    projectId: 'sportify-38715',
    storageBucket: 'sportify-38715.appspot.com',
    iosBundleId: 'com.example.toi',
  );
}
